# Julia

Let's learn a little Julia by developing a function to factor a number into primes. There are built-in functions for this kind of thing, but let's do it from scratch.

## First steps

I like to start any number crunching by doing it by hand first. So let's look at a number. How about 

```
julia> 2 * 2 * 3 * 3 * 5 * 7 * 13 * 23 * 31 * 61

712415340
```

In [28]:
n = 2 * 2 * 3 * 3 * 5 * 7 
# n = prod([2 2 3 3 5 7 13 23 31 61])
# n = prod([2, 2, 3, 3, 5, 7, 13, 23, 31, 61])
# n = prod([2; 2; 3; 3; 5; 7; 13; 23; 31; 61])
# [2  3  5  7]
# [2, 3, 5, 7]
# [2; 3; 5; 7]
# [2  3; 5  7]

1260

I'll start with the even divisors. So easy. Here are several ways to tell if a number is even:

In [37]:
@show 13 / 2;
@show 13 ÷ 2;

@show typeof(13 / 2);
@show typeof(13 ÷ 2);

@show iseven(13)
@show isodd(13)

13 / 2 = 6.5
13 ÷ 2 = 6
typeof(13 / 2) = Float64
typeof(13 ÷ 2) = Int64
iseven(13) = false
isodd(13) = true


true

In [43]:
if iseven(n) 
  n = n / 2
  println("even: ", n)
end
@show n

MethodError: MethodError: no method matching iseven(::Float64)
Closest candidates are:
  iseven(!Matched::Integer) at int.jl:125
  iseven(!Matched::Missing) at missing.jl:100

In [53]:
n = 660

660

In [56]:
if n/2 == n÷2 
  n = n / 2
  println("even: ", n)
else
  println("It's odd, man: ", n)
end
@show n

It's odd, man: 165.0
n = 165.0


165.0

In [59]:
d = 3
notfound = true
while notfound
  if n/d == n÷d
    notfound = false
    n /= d
  else
    d += 2
  end
end
@show n d

n = 1.0
d = 11


11

In [7]:
function primes(n)
  
  if n == 1 
    return n
  end
  
  if n/2 == n÷2 
    n = n / 2
    @show n 2
  else
    d = 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        n /= d
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
    @show n d
  end # else
  primes(n)
end

primes (generic function with 1 method)

In [10]:
function primes(n)
  
  if n == 1 
    return n
    
  elseif n/2 == n÷2 
    n = n / 2
    @show n 2
    
  else
    d = 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        n /= d
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
    @show n d
    
  end # else
  
  primes(n)
  
end

primes (generic function with 1 method)

In [48]:
function primes(n, theprimes)
  
  if n == 1 
    return theprimes
    
  elseif n/2 == n÷2 
    n = n / 2
    if haskey(theprimes, 2)
      theprimes[2] += 1
    else
      push!(theprimes, 2 => 1)
    end
#     @show n 2
    
  else
    d = 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        n /= d
        if haskey(theprimes, d)
          theprimes[d] += 1
        else
          push!(theprimes, d => 1)
        end
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  primes(n, theprimes)
  
end

primes (generic function with 2 methods)

In [18]:
dict = Dict(2 => 3, 3 => 4)

Dict{Int64, Int64} with 2 entries:
  2 => 3
  3 => 4

In [25]:
keys(dict)
haskey(dict,2)
haskey(dict,5)
dict[2] += 1

4

In [26]:
dict[2]

4

In [42]:
n = 1025

1025

In [43]:
theprimes = Dict()
p = primes(n, theprimes)

n = 205.0
d = 5
n = 41.0
d = 5
n = 1.0
d = 41


Dict{Any, Any} with 2 entries:
  5  => 2
  41 => 1

In [44]:
methods(primes)

# 2 methods for generic function "primes":
[1] primes(n) in Main at In[10]:1
[2] primes(n, theprimes) in Main at In[28]:1

In [45]:
function primes(n)
  theprimes = Dict()
  primes(n, theprimes)
end

primes (generic function with 2 methods)

In [50]:
primes(323232)

Dict{Any, Any} with 5 entries:
  7  => 1
  37 => 1
  13 => 1
  2  => 5
  3  => 1

A `Dict` is not ordered, so it can't be sorted. That takes away some utility and opportunity for speedups. Let's do an array. 

In [1]:
function primes2(n, theprimes=[1])
  
  if n == 1 
    return theprimes
    
  elseif n/2 == n÷2 
    n /= 2
    push!(theprimes, 2)
#     @show n 2
    
  else
    d = 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        n /= d
        push!(theprimes, d)
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  primes2(n, theprimes)
  
end

primes2 (generic function with 2 methods)

In [2]:
methods(primes2)

# 2 methods for generic function "primes2":
[1] primes2(n) in Main at In[1]:1
[2] primes2(n, theprimes) in Main at In[1]:1

In [3]:
primes2(32000)

12-element Array{Int64,1}:
 1
 2
 2
 2
 2
 2
 2
 2
 2
 5
 5
 5

In [1]:
function primes2(n, theprimes=[])
  
  if n == 1 
    return theprimes
    
  elseif n/2 == n÷2 
    n /= 2
    push!(theprimes, 2)
#     @show n 2
    
  else
    d = maximum(theprimes)
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        n /= d
        push!(theprimes, d)
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  primes2(n, theprimes)
  
end

primes2 (generic function with 2 methods)

In [2]:
primes2(33)

ArgumentError: ArgumentError: reducing over an empty collection is not allowed

In [9]:
function primes2(n, theprimes=[])
  
  if n == 1 
    return theprimes
    
  elseif n/2 == n÷2 
    n /= 2
    push!(theprimes, 2)
#     @show n 2
    
  else
    d = length(theprimes) >= 1 ? maximum(theprimes) : 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        n /= d
        push!(theprimes, d)
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  println(theprimes)
  
  primes2(n, theprimes)
  
end

primes2 (generic function with 2 methods)

In [2]:
primes3(n)=primes3([n])

primes3 (generic function with 2 methods)

In [16]:
function primes3(theprimes)
  
  println(theprimes)


  n = theprimes[end]
  
  if n == 1 
    return theprimes
    
  elseif n/2 == n÷2 
    theprimes[end] = 2
    push!(theprimes, n÷2)
#     @show n 2
    
  else
    d = length(theprimes) >= 1 ? maximum(theprimes) : 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        theprimes[end] = d
        push!(theprimes, n÷d)
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  
  primes3(theprimes)
  
end

primes3 (generic function with 5 methods)

In [8]:
function primes3(theprimes::Vector)
  
  println(theprimes)


  n = theprimes[end]
  
  if n == 1 
    return theprimes
    
  elseif n/2 == n÷2 
    theprimes[end] = 2
    push!(theprimes, n÷2)
#     @show n 2
    
  else
    d = length(theprimes) > 1 ? maximum(theprimes[1:end-1]) : 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        theprimes[end] = d
        push!(theprimes, n÷d)
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  
  primes3(theprimes)
  
end

primes3 (generic function with 1 method)

In [9]:
primes3(n)=primes3([n])

primes3 (generic function with 2 methods)

In [ ]:
primes3(7668)

In [15]:
BigInt(7625597484987)÷3 

2541865828329

In [7]:
theprimes=[9]
done = false

while !done 
  
  println(theprimes)

  n = theprimes[end]
  
  if n/2 == n÷2 
    theprimes[end] = 2
    push!(theprimes, n÷2)
#     @show n 2
    
  else
    d = length(theprimes) > 1 ? maximum(theprimes[1:end-1]) : 3
    notfound = true
    while notfound
      if n/d == n÷d
        notfound = false
        theprimes[end] = d
        push!(theprimes, n÷d)
      else
        d += 2
      end # if n/d == n÷d
    end # while notfound
#     @show n d
    
  end # else
  
  done = theprimes[end] == 1
  
end

[9]
[3, 3]


In [10]:
primes4(n) = 
  begin
    theprimes=[n]
    done = false

    while !done 

      println(theprimes)

      n = theprimes[end]

      if n/2 == n÷2 
        theprimes[end] = 2
        push!(theprimes, n÷2)
    #     @show n 2

      else
        d = length(theprimes) > 1 ? maximum(theprimes[1:end-1]) : 3
        notfound = true
        while notfound
          if n/d == n÷d
            notfound = false
            theprimes[end] = d
            push!(theprimes, n÷d)
          else
            d += 2
          end # if n/d == n÷d
        end # while notfound
    #     @show n d

      end # else

      done = theprimes[end] == 1

    end
  end

primes4 (generic function with 1 method)

In [ ]:
primes4(3^37)

In [1]:
import Pkg; Pkg.status()

Status `~/Library/Mobile Documents/com~apple~CloudDocs/iDocuments/0.course/resources.thermodynamics/YOUcanDoThermodynamics/Ti2-broken/notebooks/Project.toml`
  [e084ae63] CoolProp v0.0.0 `https://github.com/CoolProp/CoolProp.jl.git#master`
  [3a141323] PolynomialRoots v1.0.0
  [1986cc42] Unitful v1.5.0


In [2]:
Pkg.add("Primes")

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


    Fetching: [==============>                          ]  34

    Fetching: [============================>

Fetching: [========================================>]  100.0 %

  Resolving package versions...
  Installed Primes ─ v0.5.0
Updating `~/Library/Mobile Documents/com~apple~CloudDocs/iDocuments/0.course/resources.thermodynamics/YOUcanDoThermodynamics/Ti2-broken/notebooks/Project.toml`
  [27ebfcd6] + Primes v0.5.0
Updating `~/Library/Mobile Documents/com~apple~CloudDocs/iDocuments/0.course/resources.thermodynamics/YOUcanDoThermodynamics/Ti2-broken/notebooks/Manifest.toml`
  [27ebfcd6] + Primes v0.5.0


In [5]:
using Primes

In [6]:
factor(100) |> collect

2-element Array{Pair{Int64,Int64},1}:
 2 => 2
 5 => 2

In [8]:
factor(Vector, 1000)

6-element Array{Int64,1}:
 2
 2
 2
 5
 5
 5

In [ ]:
primes4(1000)

In [3]:
a = 5 > 6 && "true" || "not true"

"not true"

In [4]:
a

"not true"

In [12]:
ismersenneprime(2^11 - 1)

false

In [8]:
factor(65536)

2^16